name: CD

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # Set up environment
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci

      # Build and run tests
      - name: Build IDE
        run: npm run build
      - name: Build interop
        run: npm run interop
      - name: Run tests
        run: npm test

      # Deploy to GitHub Pages
      - name: Prepare deployment
        run: |
          rm ./out/tscript.js
          mkdir ./out/distribution
          mv ./src/ide/redirect.html ./out/distribution/index.html
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          branch: gh-pages
          folder: ./out
          single-commit: true
          git-config-name: github-actions[bot]
          git-config-email: 41898282+github-actions[bot]@users.noreply.github.com
